# AUTO-GENERATED by nixos-anywhere --generate-hardware-config
# (which calls nixos-generate-config --show-hardware-config --no-filesystems
#  on the target during install).
#
# Do NOT hand-edit.
#   - Manual settings belong in default.nix.
#   - Filesystem layout belongs in disko.nix.
#
# Regenerate by re-running the bootstrap recipe.
#
# Pre-bootstrap stub form: this file currently sets only
# `nixpkgs.hostPlatform` so `nix flake check` evaluates before Metis
# is installed. After the first `just bootstrap metis …` run,
# nixos-anywhere overwrites this file with nixos-generate-config's
# --no-filesystems output, which carries its own banner — that banner
# is sufficient; do not re-add this stub comment after install.
{ lib, ... }:

{
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
