# AUTO-GENERATED by nixos-anywhere --generate-hardware-config
# (which calls nixos-generate-config --show-hardware-config --no-filesystems
#  on the target during install).
#
# Do NOT hand-edit.
#   - Manual settings belong in default.nix.
#   - Filesystem layout belongs in disko.nix.
#
# Regenerate by re-running the bootstrap recipe.
{ lib, ... }:
{
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
