#!/usr/bin/env bash
# Enforces ADR-023's "do not hand-edit hardware-configuration.nix" rule.
#
# Wired into the pre-commit framework via parts/checks.nix; the framework
# filters tracked files through the configured `files` regex
# (^hosts/[^/]+/hardware-configuration\.nix$) and passes the matches as
# positional args. The regex deliberately does NOT match
# hosts/nixos-vm/hardware.nix — nixos-vm is the legacy two-file exception
# carved out by ADR-023 and remains unenforced.
#
# Each matched file must carry either:
#   - the stub form's banner ("AUTO-GENERATED by nixos-anywhere"), present
#     in the pre-bootstrap stub before nixos-anywhere first runs; or
#   - nixos-generate-config's own banner ("Do not modify this file"),
#     present after nixos-anywhere --generate-hardware-config overwrites
#     the stub during install.
#
# A file lacking both is assumed to have been hand-edited and the commit
# is blocked. Override (e.g. for legitimate one-off fixes) with:
#   git commit --no-verify
#
# See docs/decisions/ADR-023 for the rule, ADR-025 for this framework.

set -euo pipefail

failures=0
for file in "$@"; do
  # head -n 20 gives the banner room to live; both expected forms are
  # at the very top of the file. 2>/dev/null in case the file was
  # staged-then-deleted on disk.
  if ! head -n 20 "$file" 2>/dev/null |
    grep -qE 'AUTO-GENERATED by nixos-anywhere|Do not modify this file'; then
    echo "ERROR: $file is missing the auto-generated banner." >&2
    echo "  Per ADR-023, hardware-configuration.nix must be auto-generated, not hand-edited." >&2
    echo "  Regenerate via:" >&2
    # The trailing backslash is a literal — it renders the regenerate
    # command as a copy-pasteable two-line invocation. Inside single
    # quotes it stays verbatim; SC1003 misreads it as a botched quote-escape.
    # shellcheck disable=SC1003
    echo '    nixos-anywhere --generate-hardware-config nixos-generate-config \' >&2
    echo "                   $file" >&2
    failures=$((failures + 1))
  fi
done

if [[ $failures -gt 0 ]]; then
  echo >&2
  echo "$failures hardware-configuration.nix file(s) failed the banner check." >&2
  echo "Override (intentional hand-edit): git commit --no-verify" >&2
  exit 1
fi

exit 0
